set(_CATKIN_CURRENT_PACKAGE "liblms1xx")
set(liblms1xx_MAINTAINER "kp <kp@todo.todo>")
set(liblms1xx_DEPRECATED "")
set(liblms1xx_VERSION "0.0.0")
set(liblms1xx_BUILD_DEPENDS "roscpp" "sensor_msgs")
set(liblms1xx_RUN_DEPENDS "roscpp" "sensor_msgs")
set(liblms1xx_BUILDTOOL_DEPENDS "catkin")