DATA_TYPES = ("GET_STATUS", "R_GET_STATUS" , "GET_SONAR_1", "R_GET_SONAR_1", "GET_SONAR", "R_GET_SONAR","SET_FNR",  "R_SET_FNR",
	"SET_THROTTLE", "R_SET_THROTTLE","SET_SPEED", "R_SET_SPEED","GET_SPEED", "R_GET_SPEED","SET_STEERING", "R_SET_STEERING",
	"GET_STEERING", "R_GET_STEERING","SET_LIGHTS", "R_SET_LIGHTS","GET_BATTERY", "R_GET_BATTERY","STOP",  "R_STOP")

DATA_CODES ={ "GET_STATUS" : (0x00, 0), "GET_SONAR_1" : (0x02, 1), "GET_SONAR" : (0x04, 0), "SET_FNR" : (0x06, 1), 
	"SET_THROTTLE" : (0x08, 2),"SET_SPEED" : (0x0A, 2), "GET_SPEED" : (0x0C, 0), "SET_STEERING" :(0x0E, 1), 
	"GET_STEERING" : (0x10, 0), "SET_LIGHTS" : (0x12, 4), "GET_BATTERY" : (0x14, 0),"STOP" : (0x16, 0), 
	"R_GET_STATUS" : (0x01, 0), "R_GET_SONAR_1" : (0x03, 2), "R_GET_SONAR" : (0x05, 12), "R_SET_FNR" : (0x07, 1),
	"R_SET_THROTTLE" :(0x09, 1), "R_SET_SPEED" : (0x0B, 1), "R_GET_SPEED" : (0x0D, 4), "R_SET_STEERING" : (0x0F, 2),
	"R_GET_STEERING" : (0x11, 2), "R_SET_LIGHTS" : (0x13, 1), "R_GET_BATTERY" : (0x15, 4), "R_STOP" :(0x17, 1)}

 



